package com.kelimio.api.importpipeline.infrastructure.xlsx

/** A fail-closed rejection with a stable, non-sensitive machine code. */
class XlsxRejectedException(
    val code: XlsxRejectionCode,
) : IllegalArgumentException("XLSX rejected: ${code.name}")

enum class XlsxRejectionCode {
    INVALID_FILE_NAME,
    INVALID_MEDIA_TYPE,
    UPLOAD_TOO_LARGE,
    INVALID_ZIP_SIGNATURE,
    CORRUPT_PACKAGE,
    TOO_MANY_ZIP_ENTRIES,
    INVALID_ZIP_ENTRY_NAME,
    DUPLICATE_ZIP_ENTRY,
    CASE_FOLDING_ZIP_ENTRY_COLLISION,
    ZIP_ENTRY_TOO_LARGE,
    TOTAL_INFLATED_SIZE_EXCEEDED,
    SUSPICIOUS_COMPRESSION_RATIO,
    XML_SECURITY_VIOLATION,
    ACTIVE_CONTENT,
    EXTERNAL_CONTENT,
    UNSUPPORTED_SHEET_TYPE,
    INVALID_PACKAGE_TYPE,
    TOO_MANY_SHEETS,
    TOO_MANY_COLUMNS,
    TOO_MANY_SEMANTIC_ROWS,
    CELL_TEXT_TOO_LONG,
    TOTAL_TEXT_SIZE_EXCEEDED,
    TOO_MANY_SHARED_STRINGS,
    TOO_MANY_STYLE_RECORDS,
    FORMULA_CELL,
    HIDDEN_SHEET,
    HIDDEN_ROW,
    HIDDEN_COLUMN,
    INVALID_SHEET_NAME,
    INVALID_CELL_REFERENCE,
    MALFORMED_WORKSHEET,
    PARSE_DEADLINE_EXCEEDED,
    TEMPORARY_STORAGE_FAILURE,
}
